# Generated by Django 6.0.1 on 2026-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLiquidityInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_on_date', models.DateField(unique=True)),
                ('funds_liquid_option', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('funds_overnight_option', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('funds_ncds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liquidity Input (Daily)',
                'verbose_name_plural': 'Liquidity Inputs (Daily)',
                'ordering': ['-as_on_date'],
            },
        ),
    ]
