# Generated by Django 6.0.1 on 2026-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdentry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='fd_attachments/'),
        ),
    ]
