# Generated by Django 6.0.1 on 2026-02-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0002_fdentry_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdentry',
            name='bank_name',
        ),
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('fd_made_bank', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'bank_name', 'fd_made_bank'],
                'unique_together': {('bank_name', 'fd_made_bank', 'category')},
            },
        ),
        migrations.AddField(
            model_name='fdentry',
            name='bank_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fd_entries', to='fd.bankmaster'),
            preserve_default=False,
        ),
    ]
