# Generated by Django 6.0.1 on 2026-02-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0003_remove_fdentry_bank_name_bankmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdentry',
            name='bank_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fd.bankmaster'),
        ),
    ]
