# Generated by Django 6.0.1 on 2026-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0004_alter_fdentry_bank_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fdentry',
            old_name='amount',
            new_name='interest_actually_due',
        ),
        migrations.RemoveField(
            model_name='fdentry',
            name='fd_number',
        ),
        migrations.RemoveField(
            model_name='fdentry',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='fdentry',
            name='amount_od',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='amt_expected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='days_bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='fd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fdentry',
            name='fd_nature',
            field=models.CharField(blank=True, choices=[('Callable', 'Callable'), ('Non Callable', 'Non Callable')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='fd_number_receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='fd_type',
            field=models.CharField(blank=True, choices=[('With lien', 'With lien'), ('Without lien', 'Without lien')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='margin_of_od',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='maturity_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fdentry',
            name='od_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='percentage_bucket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='rate_of_od',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fdentry',
            name='system_fd_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='tds_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fdentry',
            name='term_loan_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdentry',
            name='term_loan_with',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
