# Generated by Django 6.0.1 on 2026-02-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0005_rename_amount_fdentry_interest_actually_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=5)),
                ('fd_type', models.CharField(max_length=3)),
                ('last_no', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('fy', 'fd_type')},
            },
        ),
    ]
