# Generated by Django 6.0.1 on 2026-02-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0006_fdnumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdentry',
            name='fd_auto_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
