# Generated by Django 6.0.1 on 2026-02-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0007_fdentry_fd_auto_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fdnumbersequence',
            old_name='fd_type',
            new_name='fd_type_code',
        ),
        migrations.AlterUniqueTogether(
            name='fdnumbersequence',
            unique_together={('fy', 'fd_type_code')},
        ),
    ]
