# Generated by Django 6.0.1 on 2026-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0008_rename_fd_type_fdnumbersequence_fd_type_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Daily Dashboard',
                'verbose_name_plural': 'DASHBOARD',
            },
        ),
    ]
