# Generated by Django 6.0.1 on 2026-02-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0009_dashboardnav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardNav',
        ),
    ]
