# Generated by Django 6.0.1 on 2026-02-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0011_trusteemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdentry',
            name='trustee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fd.trusteemaster'),
        ),
        migrations.AlterField(
            model_name='trusteemaster',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
