# Generated by Django 6.0.1 on 2026-02-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0012_fdentry_trustee_alter_trusteemaster_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankmaster',
            options={'ordering': ['sort_order', 'bank_name', 'category', 'fd_made_bank']},
        ),
        migrations.AlterUniqueTogether(
            name='bankmaster',
            unique_together={('bank_name', 'category')},
        ),
        migrations.AlterField(
            model_name='bankmaster',
            name='fd_made_bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
