# Generated by Django 6.0.1 on 2026-02-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0013_alter_bankmaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankmaster',
            options={'ordering': ['sort_order', 'bank_name', 'category']},
        ),
    ]
