# Generated by Django 6.0.1 on 2026-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0014_alter_bankmaster_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankmaster',
            options={'ordering': ['sort_order', 'bank_name']},
        ),
        migrations.AlterUniqueTogether(
            name='bankmaster',
            unique_together={('bank_name',)},
        ),
        migrations.AlterField(
            model_name='bankmaster',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
