# Generated by Django 6.0.1 on 2026-02-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fd', '0010_delete_dashboardnav'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestIncomeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Apr–Jun)'), ('Q2', 'Q2 (Jul–Sep)'), ('Q3', 'Q3 (Oct–Dec)'), ('Q4', 'Q4 (Jan–Mar)')], max_length=2)),
                ('as_on_date', models.DateField()),
                ('upload_file', models.FileField(upload_to='interest_income_uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interest Income Data',
                'verbose_name_plural': 'Interest Income Data',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCenter',
            fields=[
            ],
            options={
                'verbose_name': 'Reports',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fd.fdentry',),
        ),
        migrations.CreateModel(
            name='InterestIncomeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd_number_receipt', models.CharField(db_index=True, max_length=150)),
                ('is_matched_fd', models.BooleanField(default=False)),
                ('opening_interest_accrued', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('additions_during_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unbooked_interest_income_on_maturity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_income_on_fd_at_maturity_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interest_income_self_calculated', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('difference_t_u', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('term_of_maturity', models.CharField(blank=True, max_length=120, null=True)),
                ('recoverable_opening', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('recoverable_additions', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('recoverable_deletion', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('recoverable_closing', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tds_opening', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tds_additions_during_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tds_additions_on_unbooked_tds', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tds_closing', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interest_as_per_calculation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('basis_of_calculation', models.TextField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reports.interestincomeupload')),
            ],
            options={
                'verbose_name': 'Interest Income Line',
                'verbose_name_plural': 'Interest Income Lines',
                'ordering': ['fd_number_receipt'],
                'unique_together': {('upload', 'fd_number_receipt')},
            },
        ),
    ]
